CREATE DATABASE DAWEB25
GO
USE DAWEB25
GO
-- Loại mặt hàng
CREATE TABLE LoaiMH (
    MaLMH UNIQUEIDENTIFIER PRIMARY KEY,
    TenLMH NVARCHAR(100) NOT NULL
);
GO
-- Mặt hàng
CREATE TABLE MatHang (
    MaMH UNIQUEIDENTIFIER PRIMARY KEY,
    TenMH NVARCHAR(100) NOT NULL,
    MoTaMH NVARCHAR(MAX),
    GiaBan DECIMAL(18,2),
    AnhMH NVARCHAR(255),
    MaLMH UNIQUEIDENTIFIER FOREIGN KEY REFERENCES LoaiMH(MaLMH)
);
GO
-- Khách hàng
CREATE TABLE KhachHang (
    MaKH UNIQUEIDENTIFIER PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    DienThoai NVARCHAR(20),
    Email NVARCHAR(100),
    DiaChi NVARCHAR(255)
);
GO
-- Đơn hàng
CREATE TABLE DonHang (
    MaDH VARCHAR(10) PRIMARY KEY,
    NgayBan DATE,
    MaKH UNIQUEIDENTIFIER FOREIGN KEY REFERENCES KhachHang(MaKH)
);
GO
-- Chi tiết đơn hàng
CREATE TABLE CTDH (
    MaDH VARCHAR(10),
    MaMH UNIQUEIDENTIFIER,
    SLB INT,
    DGB DECIMAL(18,2),
    PRIMARY KEY (MaDH, MaMH),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaMH) REFERENCES MatHang(MaMH)
);
