using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CMS.DataAccess
{
    /// <summary>
    /// Controller class for CTDH
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CtdhController
    {
        // Preload our schema..
        Ctdh thisSchemaLoad = new Ctdh();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CtdhCollection FetchAll()
        {
            CtdhCollection coll = new CtdhCollection();
            Query qry = new Query(Ctdh.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CtdhCollection FetchByID(object MaDH)
        {
            CtdhCollection coll = new CtdhCollection().Where("MaDH", MaDH).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CtdhCollection FetchByQuery(Query qry)
        {
            CtdhCollection coll = new CtdhCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaDH)
        {
            return (Ctdh.Delete(MaDH) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaDH)
        {
            return (Ctdh.Destroy(MaDH) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string MaDH,Guid MaMH)
        {
            Query qry = new Query(Ctdh.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("MaDH", MaDH).AND("MaMH", MaMH);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string MaDH,Guid MaMH,int? Slb,decimal? Dgb)
	    {
		    Ctdh item = new Ctdh();
		    
            item.MaDH = MaDH;
            
            item.MaMH = MaMH;
            
            item.Slb = Slb;
            
            item.Dgb = Dgb;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string MaDH,Guid MaMH,int? Slb,decimal? Dgb)
	    {
		    Ctdh item = new Ctdh();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaDH = MaDH;
				
			item.MaMH = MaMH;
				
			item.Slb = Slb;
				
			item.Dgb = Dgb;
				
	        item.Save(UserName);
	    }
    }
}
