using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CMS.DataAccess
{
    /// <summary>
    /// Controller class for LoaiMH
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LoaiMHController
    {
        // Preload our schema..
        LoaiMH thisSchemaLoad = new LoaiMH();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LoaiMHCollection FetchAll()
        {
            LoaiMHCollection coll = new LoaiMHCollection();
            Query qry = new Query(LoaiMH.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiMHCollection FetchByID(object MaLMH)
        {
            LoaiMHCollection coll = new LoaiMHCollection().Where("MaLMH", MaLMH).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiMHCollection FetchByQuery(Query qry)
        {
            LoaiMHCollection coll = new LoaiMHCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaLMH)
        {
            return (LoaiMH.Delete(MaLMH) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaLMH)
        {
            return (LoaiMH.Destroy(MaLMH) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid MaLMH,string MoTaLMH,string TenLMH)
	    {
		    LoaiMH item = new LoaiMH();
		    
            item.MaLMH = MaLMH;
            
            item.MoTaLMH = MoTaLMH;
            
            item.TenLMH = TenLMH;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid MaLMH,string MoTaLMH,string TenLMH)
	    {
		    LoaiMH item = new LoaiMH();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaLMH = MaLMH;
				
			item.MoTaLMH = MoTaLMH;
				
			item.TenLMH = TenLMH;
				
	        item.Save(UserName);
	    }
    }
}
