using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CMS.DataAccess
{
    /// <summary>
    /// Controller class for KhachHang
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class KhachHangController
    {
        // Preload our schema..
        KhachHang thisSchemaLoad = new KhachHang();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public KhachHangCollection FetchAll()
        {
            KhachHangCollection coll = new KhachHangCollection();
            Query qry = new Query(KhachHang.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public KhachHangCollection FetchByID(object MaKH)
        {
            KhachHangCollection coll = new KhachHangCollection().Where("MaKH", MaKH).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public KhachHangCollection FetchByQuery(Query qry)
        {
            KhachHangCollection coll = new KhachHangCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaKH)
        {
            return (KhachHang.Delete(MaKH) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaKH)
        {
            return (KhachHang.Destroy(MaKH) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public KhachHang Insert(KhachHang item)
	    {
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public KhachHang Update(KhachHang item)
	    {	
	        item.Save(UserName);
            return item;
	    }
    }
}
